import os
import gzip
import re
import datetime

# Configuration
SOURCE_DIR = 'html'
OUTPUT_FILE = os.path.join('src', 'ESPSWebUI.h')

# Mime types
MIME_TYPES = {
    '.html': 'text/html',
    '.css': 'text/css',
    '.js': 'application/javascript',
    '.json': 'application/json',
    '.png': 'image/png',
    '.ico': 'image/x-icon',
    '.gz': 'application/x-gzip'
}

def minify_html(content):
    # Basic HTML minification
    content = re.sub(r'<!--.*?-->', '', content, flags=re.DOTALL) # Remove comments
    content = re.sub(r'\s+', ' ', content) # Collapse whitespace
    content = re.sub(r'>\s+<', '><', content) # Remove whitespace between tags
    return content

def minify_css(content):
    # Basic CSS minification
    content = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL) # Remove comments
    content = re.sub(r'\s+', ' ', content) # Collapse whitespace
    content = re.sub(r'\s*([:;{}])\s*', r'\1', content) # Remove whitespace around symbols
    return content

def minify_js(content):
    # Basic JS minification (safe subset)
    # We avoid regex for comments as it's risky with strings (e.g. "http://...")
    # Just collapse multiple spaces and trim lines
    lines = content.split('\n')
    minified_lines = []
    for line in lines:
        line = line.strip()
        if line and not line.startswith('//'):
             minified_lines.append(line)
    return '\n'.join(minified_lines)

def get_c_variable_name(filename):
    clean_name = re.sub(r'[^a-zA-Z0-9]', '_', filename)
    return f"file_{clean_name}"

def create_header():
    print(f"Building Web UI from {SOURCE_DIR}...")

    files_data = []

    for root, dirs, files in os.walk(SOURCE_DIR):
        for file in files:
            ext = os.path.splitext(file)[1]
            if ext not in MIME_TYPES:
                continue

            file_path = os.path.join(root, file)
            rel_path = os.path.relpath(file_path, SOURCE_DIR)
            # Normalise path to usage in webserver
            web_path = '/' + rel_path.replace('\\', '/')

            # Special handling to match previous gulp/code behavior
            if web_path == '/UpdRecipe.json':
                # The C++ code previously mapped /UpdRecipe/ to this file
                # We will handle this in the route registration
                pass

            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                # Read as binary for images, text for others
                if ext in ['.png', '.ico']:
                    with open(file_path, 'rb') as fb:
                        content_raw = fb.read()
                        content_min = content_raw
                else:
                    content_raw = f.read()
                    if ext == '.html':
                        content_min = minify_html(content_raw).encode('utf-8')
                    elif ext == '.css':
                        content_min = minify_css(content_raw).encode('utf-8')
                    elif ext == '.js':
                         content_min = minify_js(content_raw).encode('utf-8')
                    else:
                        content_min = content_raw.encode('utf-8')

            # Gzip
            content_gz = gzip.compress(content_min)

            var_name = get_c_variable_name(rel_path)
            files_data.append({
                'path': web_path,
                'var': var_name,
                'data': content_gz,
                'mime': MIME_TYPES[ext],
                'length': len(content_gz)
            })
            print(f"Processed {rel_path}: {len(content_raw)} -> {len(content_min)} -> {len(content_gz)} bytes")

    # Generate Header Content
    header_content = []
    header_content.append("#pragma once")
    header_content.append("#include <Arduino.h>")
    header_content.append("#include <ESPAsyncWebServer.h>")
    header_content.append("")
    header_content.append(f"// Generated by build_web_ui.py on {datetime.datetime.now()}")
    header_content.append("")

    # Write data arrays
    for item in files_data:
        hex_data = ', '.join(f"0x{b:02x}" for b in item['data'])
        header_content.append(f"const uint8_t {item['var']}[] PROGMEM = {{ {hex_data} }};")
        header_content.append(f"const size_t {item['var']}_len = {item['length']};")
        header_content.append("")

    # Write Init function
    header_content.append("void InitWebUI(AsyncWebServer& server) {")

    for item in files_data:
        path = item['path']
        var = item['var']
        length = f"{var}_len"
        mime = item['mime']

        # Determine routes
        routes = [path]
        if path == '/index.html':
            routes.append('/')

        # Special case for UpdRecipe.json if needed (Logic from WebMgr.cpp: /UpdRecipe/ -> /UpdRecipe.json)
        if path == '/UpdRecipe.json':
            routes.append('/UpdRecipe/')

        for route in routes:
            header_content.append(f'    server.on("{route}", HTTP_GET, [](AsyncWebServerRequest *request) {{')
            header_content.append(f'        AsyncWebServerResponse *response = request->beginResponse_P(200, "{mime}", {var}, {length});')
            header_content.append('        response->addHeader("Content-Encoding", "gzip");')
            header_content.append('        request->send(response);')
            header_content.append('    });')

    header_content.append("}")

    with open(OUTPUT_FILE, 'w') as f:
        f.write('\n'.join(header_content))

    print(f"Generated {OUTPUT_FILE}")

if __name__ == '__main__':
    create_header()
